texto = ("Hola Mundo")
print(texto.upper())
print(texto.lower())
print(texto.find("l"))
print(texto.find("a"))
print(texto.replace("Mun", "Luis Dávila"))
nuevotexto = texto.replace("Mun", "Luis Dávila")
print(texto, nuevotexto)
print("Mundo" in texto)